// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class BotConfiguracion
{
    public int Id { get; set; }

    public Guid TenantId { get; set; }

    public bool Activo { get; set; }

    public string NombreBot { get; set; }

    public string TonoConversacion { get; set; }

    public string SaludoInicial { get; set; }

    public string TelefonoDerivacion { get; set; }

    public string DirectricesExtra { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual Tenant Tenant { get; set; }
}