// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Cliente : IAuditableEntity, IFullAuditableEntity, ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Telefono { get; set; }

    public string WhatsappId { get; set; }

    public string Email { get; set; }

    public string EtapaCrm { get; set; }

    public string Notas { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual ICollection<Contrato> Contratos { get; set; } = new List<Contrato>();

    public virtual ICollection<DocumentosAdjunto> DocumentosAdjuntos { get; set; } = new List<DocumentosAdjunto>();

    public virtual Tenant Tenant { get; set; }

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();
}