// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Contrato
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public Guid PropiedadId { get; set; }

    public Guid InquilinoId { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaFin { get; set; }

    public decimal MontoMensual { get; set; }

    public string Moneda { get; set; }

    public short DiaVencimientoPago { get; set; }

    public string Estado { get; set; }

    public string ArchivoContratoUrl { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual Cliente Inquilino { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();

    public virtual Propiedades Propiedad { get; set; }

    public virtual Tenant Tenant { get; set; }
}