// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Inmo24.Domain.Models;

public partial class InmobiliariaContext : DbContext
{
    public InmobiliariaContext(DbContextOptions<InmobiliariaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BotConfiguracion> BotConfiguracions { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Contrato> Contratos { get; set; }

    public virtual DbSet<DocumentosAdjunto> DocumentosAdjuntos { get; set; }

    public virtual DbSet<EstadosComerciale> EstadosComerciales { get; set; }

    public virtual DbSet<FasesCarga> FasesCargas { get; set; }

    public virtual DbSet<N8nChatHistorialBot> N8nChatHistorialBots { get; set; }

    public virtual DbSet<Pago> Pagos { get; set; }

    public virtual DbSet<PropiedadHistorialCambio> PropiedadHistorialCambios { get; set; }

    public virtual DbSet<PropiedadImagene> PropiedadImagenes { get; set; }

    public virtual DbSet<Propiedades> Propiedades { get; set; }

    public virtual DbSet<Tenant> Tenants { get; set; }

    public virtual DbSet<TiposOperacion> TiposOperacions { get; set; }

    public virtual DbSet<TiposPropiedad> TiposPropiedads { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<Venta> Ventas { get; set; }

    public virtual DbSet<Visita> Visitas { get; set; }

    public virtual DbSet<Zona> Zonas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("pgcrypto")
            .HasPostgresExtension("uuid-ossp")
            .HasPostgresExtension("vector");

        modelBuilder.Entity<BotConfiguracion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("bot_configuracion_pkey");

            entity.ToTable("bot_configuracion");

            entity.HasIndex(e => e.TenantId, "uk_bot_configuracion_tenant").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Activo)
                .HasDefaultValue(true)
                .HasColumnName("activo");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.DirectricesExtra).HasColumnName("directrices_extra");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.NombreBot)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValueSql("'InnoBot'::character varying")
                .HasColumnName("nombre_bot");
            entity.Property(e => e.SaludoInicial)
                .IsRequired()
                .HasDefaultValueSql("'Hola buenas ✌🏼 Soy {NombreBot} de {NombreInmobiliaria}, tu inmobiliaria de confianza. ¿En qué puedo ayudarte hoy?'::text")
                .HasColumnName("saludo_inicial");
            entity.Property(e => e.TelefonoDerivacion)
                .HasMaxLength(50)
                .HasColumnName("telefono_derivacion");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.TonoConversacion)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValueSql("'Argentino, amable, profesional.'::character varying")
                .HasColumnName("tono_conversacion");

            entity.HasOne(d => d.Tenant).WithOne(p => p.BotConfiguracion)
                .HasForeignKey<BotConfiguracion>(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("bot_configuracion_tenant_id_fkey");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("clientes_pkey");

            entity.ToTable("clientes");

            entity.HasIndex(e => new { e.TenantId, e.Telefono }, "clientes_tenant_id_telefono_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.Apellido)
                .HasMaxLength(150)
                .HasColumnName("apellido");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.EtapaCrm)
                .HasMaxLength(50)
                .HasDefaultValueSql("'NEW'::character varying")
                .HasColumnName("etapa_crm");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("nombre");
            entity.Property(e => e.Notas).HasColumnName("notas");
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("telefono");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.WhatsappId)
                .HasMaxLength(100)
                .HasColumnName("whatsapp_id");

            entity.HasOne(d => d.Tenant).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("clientes_tenant_id_fkey");
        });

        modelBuilder.Entity<Contrato>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("contratos_pkey");

            entity.ToTable("contratos");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.ArchivoContratoUrl).HasColumnName("archivo_contrato_url");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.DiaVencimientoPago)
                .HasDefaultValue((short)10)
                .HasColumnName("dia_vencimiento_pago");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'vigente'::character varying")
                .HasColumnName("estado");
            entity.Property(e => e.FechaFin).HasColumnName("fecha_fin");
            entity.Property(e => e.FechaInicio).HasColumnName("fecha_inicio");
            entity.Property(e => e.InquilinoId).HasColumnName("inquilino_id");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.Moneda)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("'ARS'::character varying")
                .HasColumnName("moneda");
            entity.Property(e => e.MontoMensual)
                .HasPrecision(14, 2)
                .HasColumnName("monto_mensual");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.PropiedadId).HasColumnName("propiedad_id");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.Inquilino).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.InquilinoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("contratos_inquilino_id_fkey");

            entity.HasOne(d => d.Propiedad).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.PropiedadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("contratos_propiedad_id_fkey");

            entity.HasOne(d => d.Tenant).WithMany(p => p.Contratos)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("contratos_tenant_id_fkey");
        });

        modelBuilder.Entity<DocumentosAdjunto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("documentos_adjuntos_pkey");

            entity.ToTable("documentos_adjuntos");

            entity.HasIndex(e => new { e.TenantId, e.ClienteId }, "idx_documentos_adjuntos_cliente");

            entity.HasIndex(e => e.EntidadReferenciaId, "idx_documentos_adjuntos_referencia");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.Categoria)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("categoria");
            entity.Property(e => e.ClienteId).HasColumnName("cliente_id");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.EntidadReferenciaId).HasColumnName("entidad_referencia_id");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'Pendiente'::character varying")
                .HasColumnName("estado");
            entity.Property(e => e.Extension)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("extension");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.NombreArchivo)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre_archivo");
            entity.Property(e => e.TamanioBytes).HasColumnName("tamanio_bytes");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.TipoEntidad)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("tipo_entidad");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasColumnName("url");

            entity.HasOne(d => d.Cliente).WithMany(p => p.DocumentosAdjuntos)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_documentos_adjuntos_cliente");

            entity.HasOne(d => d.Tenant).WithMany(p => p.DocumentosAdjuntos)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_documentos_adjuntos_tenant");
        });

        modelBuilder.Entity<EstadosComerciale>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("estados_comerciales_pkey");

            entity.ToTable("estados_comerciales");

            entity.HasIndex(e => e.Nombre, "estados_comerciales_nombre_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<FasesCarga>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("fases_carga_pkey");

            entity.ToTable("fases_carga");

            entity.HasIndex(e => e.Nombre, "fases_carga_nombre_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<N8nChatHistorialBot>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("n8n_chat_historial_bot_pkey");

            entity.ToTable("n8n_chat_historial_bot");

            entity.HasIndex(e => e.SessionId, "idx_n8n_chat_historial_bot_session_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Message)
                .IsRequired()
                .HasColumnType("jsonb")
                .HasColumnName("message");
            entity.Property(e => e.SessionId)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("session_id");
        });

        modelBuilder.Entity<Pago>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pagos_pkey");

            entity.ToTable("pagos");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.ComprobanteUrl).HasColumnName("comprobante_url");
            entity.Property(e => e.ContratoId).HasColumnName("contrato_id");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'pendiente'::character varying")
                .HasColumnName("estado");
            entity.Property(e => e.FechaPago).HasColumnName("fecha_pago");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MontoAbonado)
                .HasPrecision(14, 2)
                .HasColumnName("monto_abonado");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Observaciones).HasColumnName("observaciones");
            entity.Property(e => e.PeriodoAnio).HasColumnName("periodo_anio");
            entity.Property(e => e.PeriodoMes).HasColumnName("periodo_mes");

            entity.HasOne(d => d.Contrato).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.ContratoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("pagos_contrato_id_fkey");
        });

        modelBuilder.Entity<PropiedadHistorialCambio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("propiedad_historial_cambios_pkey");

            entity.ToTable("propiedad_historial_cambios");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.EstadoComAntId).HasColumnName("estado_com_ant_id");
            entity.Property(e => e.EstadoComNuevoId).HasColumnName("estado_com_nuevo_id");
            entity.Property(e => e.FaseCargaAntId).HasColumnName("fase_carga_ant_id");
            entity.Property(e => e.FaseCargaNuevaId).HasColumnName("fase_carga_nueva_id");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.Observacion).HasColumnName("observacion");
            entity.Property(e => e.PropiedadId).HasColumnName("propiedad_id");

            entity.HasOne(d => d.EstadoComAnt).WithMany(p => p.PropiedadHistorialCambioEstadoComAnts)
                .HasForeignKey(d => d.EstadoComAntId)
                .HasConstraintName("propiedad_historial_cambios_estado_com_ant_id_fkey");

            entity.HasOne(d => d.EstadoComNuevo).WithMany(p => p.PropiedadHistorialCambioEstadoComNuevos)
                .HasForeignKey(d => d.EstadoComNuevoId)
                .HasConstraintName("propiedad_historial_cambios_estado_com_nuevo_id_fkey");

            entity.HasOne(d => d.FaseCargaAnt).WithMany(p => p.PropiedadHistorialCambioFaseCargaAnts)
                .HasForeignKey(d => d.FaseCargaAntId)
                .HasConstraintName("propiedad_historial_cambios_fase_carga_ant_id_fkey");

            entity.HasOne(d => d.FaseCargaNueva).WithMany(p => p.PropiedadHistorialCambioFaseCargaNuevas)
                .HasForeignKey(d => d.FaseCargaNuevaId)
                .HasConstraintName("propiedad_historial_cambios_fase_carga_nueva_id_fkey");

            entity.HasOne(d => d.Propiedad).WithMany(p => p.PropiedadHistorialCambios)
                .HasForeignKey(d => d.PropiedadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("propiedad_historial_cambios_propiedad_id_fkey");
        });

        modelBuilder.Entity<PropiedadImagene>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("propiedad_imagenes_pkey");

            entity.ToTable("propiedad_imagenes");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.EsPrincipal)
                .HasDefaultValue(false)
                .HasColumnName("es_principal");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Orden)
                .HasDefaultValue((short)0)
                .HasColumnName("orden");
            entity.Property(e => e.PropiedadId).HasColumnName("propiedad_id");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasColumnName("url");

            entity.HasOne(d => d.Propiedad).WithMany(p => p.PropiedadImagenes)
                .HasForeignKey(d => d.PropiedadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("propiedad_imagenes_propiedad_id_fkey");
        });

        modelBuilder.Entity<Propiedades>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("propiedades_pkey");

            entity.ToTable("propiedades");

            entity.HasIndex(e => new { e.TenantId, e.Codigo }, "propiedades_tenant_id_codigo_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.AgenteId).HasColumnName("agente_id");
            entity.Property(e => e.Ambientes).HasColumnName("ambientes");
            entity.Property(e => e.Antiguedad).HasColumnName("antiguedad");
            entity.Property(e => e.Banios).HasColumnName("banios");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("codigo");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.Descripcion).HasColumnName("descripcion");
            entity.Property(e => e.DescripcionBreve)
                .HasMaxLength(500)
                .HasColumnName("descripcion_breve");
            entity.Property(e => e.Destacada)
                .HasDefaultValue(false)
                .HasColumnName("destacada");
            entity.Property(e => e.Direccion)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("direccion");
            entity.Property(e => e.Dormitorios).HasColumnName("dormitorios");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.EstadoComercialId).HasColumnName("estado_comercial_id");
            entity.Property(e => e.FaseCargaId).HasColumnName("fase_carga_id");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.Moneda)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("'USD'::character varying")
                .HasColumnName("moneda");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.NotificarLeads)
                .HasDefaultValue(false)
                .HasColumnName("notificar_leads");
            entity.Property(e => e.OperacionId).HasColumnName("operacion_id");
            entity.Property(e => e.PrecioArs)
                .HasPrecision(14, 2)
                .HasColumnName("precio_ars");
            entity.Property(e => e.PrecioUsd)
                .HasPrecision(12, 2)
                .HasColumnName("precio_usd");
            entity.Property(e => e.SuperficieCubierta)
                .HasPrecision(10, 2)
                .HasColumnName("superficie_cubierta");
            entity.Property(e => e.SuperficieTotal)
                .HasPrecision(10, 2)
                .HasColumnName("superficie_total");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.TipoId).HasColumnName("tipo_id");
            entity.Property(e => e.Titulo)
                .HasMaxLength(255)
                .HasColumnName("titulo");
            entity.Property(e => e.ZonaId).HasColumnName("zona_id");

            entity.Property(e => e.VideoUrl)
            .HasColumnName("video_url");

            entity.Property(e => e.Latitud).HasColumnName("latitud");
            entity.Property(e => e.Longitud).HasColumnName("longitud");
            entity.Property(e => e.Cocheras).HasColumnName("cocheras");

            entity.HasOne(d => d.Agente).WithMany(p => p.Propiedades)
                .HasForeignKey(d => d.AgenteId)
                .HasConstraintName("propiedades_agente_id_fkey");

            entity.HasOne(d => d.EstadoComercial).WithMany(p => p.Propiedades)
                .HasForeignKey(d => d.EstadoComercialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_prop_estado");

            entity.HasOne(d => d.FaseCarga).WithMany(p => p.Propiedades)
                .HasForeignKey(d => d.FaseCargaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_prop_fase");

            entity.HasOne(d => d.Operacion).WithMany(p => p.Propiedades)
                .HasForeignKey(d => d.OperacionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_prop_operacion");

            entity.HasOne(d => d.Tenant).WithMany(p => p.Propiedades)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("propiedades_tenant_id_fkey");

            entity.HasOne(d => d.Tipo).WithMany(p => p.Propiedades)
                .HasForeignKey(d => d.TipoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_prop_tipo");

            entity.HasOne(d => d.Zona).WithMany(p => p.Propiedades)
                .HasForeignKey(d => d.ZonaId)
                .HasConstraintName("propiedades_zona_id_fkey");
        });

        modelBuilder.Entity<Tenant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("tenants_pkey");

            entity.ToTable("tenants");

            entity.HasIndex(e => e.Slug, "tenants_slug_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.Activo)
                .HasDefaultValue(true)
                .HasColumnName("activo");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.EmailContacto)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email_contacto");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.LogoUrl).HasColumnName("logo_url");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("nombre");
            entity.Property(e => e.Plan)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'free'::character varying")
                .HasColumnName("plan");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("slug");
            entity.Property(e => e.Telefono)
                .HasMaxLength(30)
                .HasColumnName("telefono");
            entity.Property(e => e.InstanciaWa)
                 .HasColumnName("instancia_wa");

        });

        modelBuilder.Entity<TiposOperacion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("tipos_operacion_pkey");

            entity.ToTable("tipos_operacion");

            entity.HasIndex(e => e.Nombre, "tipos_operacion_nombre_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<TiposPropiedad>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("tipos_propiedad_pkey");

            entity.ToTable("tipos_propiedad");

            entity.HasIndex(e => e.Nombre, "tipos_propiedad_nombre_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("usuarios_pkey");

            entity.ToTable("usuarios");

            entity.HasIndex(e => new { e.TenantId, e.Email }, "usuarios_tenant_id_email_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.Activo)
                .HasDefaultValue(true)
                .HasColumnName("activo");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("apellido");
            entity.Property(e => e.AvatarUrl).HasColumnName("avatar_url");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.EmailVerificado)
                .HasDefaultValue(false)
                .HasColumnName("email_verificado");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'agente'::character varying")
                .HasColumnName("rol");
            entity.Property(e => e.Telefono)
                .HasMaxLength(30)
                .HasColumnName("telefono");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");
            entity.Property(e => e.UltimoLogin).HasColumnName("ultimo_login");

            entity.HasOne(d => d.Tenant).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("usuarios_tenant_id_fkey");
        });

        modelBuilder.Entity<Venta>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("ventas_pkey");

            entity.ToTable("ventas");

            entity.HasIndex(e => e.PropiedadId, "idx_ventas_propiedad");

            entity.HasIndex(e => new { e.TenantId, e.FechaVenta }, "idx_ventas_tenant_fecha");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.ComisionInmobiliaria)
                .HasPrecision(14, 2)
                .HasColumnName("comision_inmobiliaria");
            entity.Property(e => e.CompradorId).HasColumnName("comprador_id");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.Escribania)
                .HasMaxLength(255)
                .HasColumnName("escribania");
            entity.Property(e => e.FechaVenta).HasColumnName("fecha_venta");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.Moneda)
                .IsRequired()
                .HasMaxLength(10)
                .HasDefaultValueSql("'USD'::character varying")
                .HasColumnName("moneda");
            entity.Property(e => e.MontoTotal)
                .HasPrecision(14, 2)
                .HasColumnName("monto_total");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Notas).HasColumnName("notas");
            entity.Property(e => e.PropiedadId).HasColumnName("propiedad_id");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.Comprador).WithMany(p => p.Venta)
                .HasForeignKey(d => d.CompradorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ventas_comprador_id_fkey");

            entity.HasOne(d => d.Propiedad).WithMany(p => p.Venta)
                .HasForeignKey(d => d.PropiedadId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ventas_propiedad_id_fkey");

            entity.HasOne(d => d.Tenant).WithMany(p => p.Venta)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("ventas_tenant_id_fkey");
        });

        modelBuilder.Entity<Visita>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("visitas_pkey");

            entity.ToTable("visitas");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.ClienteId).HasColumnName("cliente_id");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.DireccionCasa)
                .HasMaxLength(255)
                .HasColumnName("direccion_casa");
            entity.Property(e => e.DuracionMinutos)
                .HasDefaultValue((short)60)
                .HasColumnName("duracion_minutos");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'agendada'::character varying")
                .HasColumnName("estado");
            entity.Property(e => e.FechaVisita).HasColumnName("fecha_visita");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.NombreCliente)
                .HasMaxLength(150)
                .HasColumnName("nombre_cliente");
            entity.Property(e => e.Notas).HasColumnName("notas");
            entity.Property(e => e.PropiedadId).HasColumnName("propiedad_id");
            entity.Property(e => e.TelefonoCliente)
                .HasMaxLength(50)
                .HasColumnName("telefono_cliente");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Visita)
                .HasForeignKey(d => d.ClienteId)
                .HasConstraintName("visitas_cliente_id_fkey");

            entity.HasOne(d => d.Propiedad).WithMany(p => p.Visita)
                .HasForeignKey(d => d.PropiedadId)
                .HasConstraintName("visitas_propiedad_id_fkey");

            entity.HasOne(d => d.Tenant).WithMany(p => p.Visita)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("visitas_tenant_id_fkey");
        });

        modelBuilder.Entity<Zona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("zonas_pkey");

            entity.ToTable("zonas");

            entity.HasIndex(e => new { e.TenantId, e.Nombre }, "zonas_tenant_id_nombre_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Activa)
                .HasDefaultValue(true)
                .HasColumnName("activa");
            entity.Property(e => e.CreadoEl)
                .HasDefaultValueSql("now()")
                .HasColumnName("creado_el");
            entity.Property(e => e.CreadoPor)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValueSql("'sistema'::character varying")
                .HasColumnName("creado_por");
            entity.Property(e => e.Descripcion).HasColumnName("descripcion");
            entity.Property(e => e.EliminadoEl).HasColumnName("eliminado_el");
            entity.Property(e => e.EliminadoPor)
                .HasMaxLength(255)
                .HasColumnName("eliminado_por");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasColumnName("is_deleted");
            entity.Property(e => e.ModificadoEl).HasColumnName("modificado_el");
            entity.Property(e => e.ModificadoPor)
                .HasMaxLength(255)
                .HasColumnName("modificado_por");
            entity.Property(e => e.MotivoBaja).HasColumnName("motivo_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");
            entity.Property(e => e.TenantId).HasColumnName("tenant_id");

            entity.HasOne(d => d.Tenant).WithMany(p => p.Zonas)
                .HasForeignKey(d => d.TenantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("zonas_tenant_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}