// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class N8nChatHistorialBot
{
    public int Id { get; set; }

    public string SessionId { get; set; }

    public string Message { get; set; }
}