// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Pago
{
    public Guid Id { get; set; }

    public Guid ContratoId { get; set; }

    public short PeriodoMes { get; set; }

    public short PeriodoAnio { get; set; }

    public decimal? MontoAbonado { get; set; }

    public DateTime? FechaPago { get; set; }

    public string Estado { get; set; }

    public string ComprobanteUrl { get; set; }

    public string Observaciones { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual Contrato Contrato { get; set; }
}