// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Propiedades : IAuditableEntity, IFullAuditableEntity, ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public string Codigo { get; set; }

    public int? ZonaId { get; set; }

    public string Direccion { get; set; }

    public decimal? PrecioUsd { get; set; }

    public decimal? PrecioArs { get; set; }

    public string Moneda { get; set; }

    public decimal? SuperficieTotal { get; set; }

    public decimal? SuperficieCubierta { get; set; }

    public short? Ambientes { get; set; }

    public short? Dormitorios { get; set; }

    public short? Banios { get; set; }

    public short? Antiguedad { get; set; }

    public string Descripcion { get; set; }

    public string DescripcionBreve { get; set; }

    public bool NotificarLeads { get; set; }

    public bool Destacada { get; set; }

    public Guid? AgenteId { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public short TipoId { get; set; }

    public short OperacionId { get; set; }

    public short FaseCargaId { get; set; }

    public short EstadoComercialId { get; set; }

    public string Titulo { get; set; }

    public virtual Usuario Agente { get; set; }

    public virtual ICollection<Contrato> Contratos { get; set; } = new List<Contrato>();

    public virtual EstadosComerciale EstadoComercial { get; set; }

    public virtual FasesCarga FaseCarga { get; set; }

    public virtual TiposOperacion Operacion { get; set; }

    public virtual ICollection<PropiedadHistorialCambio> PropiedadHistorialCambios { get; set; } = new List<PropiedadHistorialCambio>();

    public virtual ICollection<PropiedadImagene> PropiedadImagenes { get; set; } = new List<PropiedadImagene>();

    public virtual Tenant Tenant { get; set; }

    public virtual TiposPropiedad Tipo { get; set; }

    public virtual ICollection<Venta> Venta { get; set; } = new List<Venta>();

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();

    public virtual Zona Zona { get; set; }
}