// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class PropiedadHistorialCambio 
{
    public Guid Id { get; set; }

    public Guid PropiedadId { get; set; }

    public string Observacion { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public short? FaseCargaAntId { get; set; }

    public short? FaseCargaNuevaId { get; set; }

    public short? EstadoComAntId { get; set; }

    public short? EstadoComNuevoId { get; set; }

    public virtual EstadosComerciale EstadoComAnt { get; set; }

    public virtual EstadosComerciale EstadoComNuevo { get; set; }

    public virtual FasesCarga FaseCargaAnt { get; set; }

    public virtual FasesCarga FaseCargaNueva { get; set; }

    public virtual Propiedades Propiedad { get; set; }
}