// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class PropiedadImagene
{
    public Guid Id { get; set; }

    public Guid PropiedadId { get; set; }

    public string Url { get; set; }

    public short Orden { get; set; }

    public bool EsPrincipal { get; set; }

    public string Descripcion { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual Propiedades Propiedad { get; set; }
}