// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Tenant
{
    public Guid Id { get; set; }

    public string Nombre { get; set; }

    public string Slug { get; set; }

    public string EmailContacto { get; set; }

    public string Telefono { get; set; }

    public string LogoUrl { get; set; }

    public bool Activo { get; set; }

    public string Plan { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual ICollection<Contrato> Contratos { get; set; } = new List<Contrato>();

    public virtual ICollection<Propiedades> Propiedades { get; set; } = new List<Propiedades>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();

    public virtual ICollection<Zona> Zonas { get; set; } = new List<Zona>();
}