// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class TiposPropiedad
{
    public short Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Propiedades> Propiedades { get; set; } = new List<Propiedades>();
}