// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Usuario : IAuditableEntity, IFullAuditableEntity, ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Telefono { get; set; }

    public string Rol { get; set; }

    public bool Activo { get; set; }

    public bool EmailVerificado { get; set; }

    public DateTime? UltimoLogin { get; set; }

    public string AvatarUrl { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual ICollection<Propiedades> Propiedades { get; set; } = new List<Propiedades>();

    public virtual Tenant Tenant { get; set; }
}