// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Visita : IAuditableEntity, IFullAuditableEntity, ITenantEntity
{
    public Guid Id { get; set; }

    public Guid TenantId { get; set; }

    public Guid? ClienteId { get; set; }

    public Guid? PropiedadId { get; set; }

    public string NombreCliente { get; set; }

    public string TelefonoCliente { get; set; }

    public string DireccionCasa { get; set; }

    public DateTime FechaVisita { get; set; }

    public short? DuracionMinutos { get; set; }

    public string Estado { get; set; }

    public string Notas { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual Propiedades Propiedad { get; set; }

    public virtual Tenant Tenant { get; set; }
}