// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Inmo24.Domain.Models;

public partial class Zona : IAuditableEntity, IFullAuditableEntity, ITenantEntity
{
    public int Id { get; set; }

    public Guid TenantId { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool Activa { get; set; }

    public string CreadoPor { get; set; }

    public DateTime CreadoEl { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? ModificadoEl { get; set; }

    public bool IsDeleted { get; set; }

    public string EliminadoPor { get; set; }

    public DateTime? EliminadoEl { get; set; }

    public string MotivoBaja { get; set; }

    public virtual ICollection<Propiedades> Propiedades { get; set; } = new List<Propiedades>();

    public virtual Tenant Tenant { get; set; }
}